name: CI
on: [push, pull_request]

env:
  DEEPL_AUTH_KEY: ${{ secrets.DEEPL_AUTH_KEY }}


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.7]
        bundler: [default]
        gemfile:
          - rails-5.2
          - rails-6.0
          - rails-6.1
          - rails-master
        include:
          - { ruby: "2.7", gemfile: "rails-5.2", bundler: "default" }
          - { ruby: "2.7", gemfile: "rails-6.0", bundler: "default" }
          - { ruby: "2.7", gemfile: "rails-6.1", bundler: "default" }
          - { ruby: "2.7", gemfile: "rails-master", bundler: "default" }

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: true # runs `bundle install` and caches gems automatically
      - name: Run tests
        run: bundle exec rake test
